# vellm — cross-DJGPP build for MS-DOS 6.22 / Pentium Overdrive 83.
#
# This is the primary Makefile. It builds `vellm.exe` (and the Phase 0
# `hello.exe` smoke test) using the DJGPP cross-compiler installed under
# ~/emulators/tools/djgpp/ by tools/build-djgpp.sh.
#
# See Makefile.host for the native-Linux reference build.

# --- Toolchain ----------------------------------------------------------------

# Prepend the DJGPP cross toolchain to PATH so that `make` works regardless
# of shell state. This mirrors the retro68-build pattern from our Mac retro
# pipeline.
#
# Two dirs are needed: the main bin/ (cross-gcc + friends) and
# i586-pc-msdosdjgpp/bin/ (target-side utilities like stubedit, stubify, exe2coff).
DJGPP_ROOT := $(HOME)/emulators/tools/djgpp
export PATH := $(DJGPP_ROOT)/bin:$(DJGPP_ROOT)/i586-pc-msdosdjgpp/bin:$(PATH)

CC       := i586-pc-msdosdjgpp-gcc
STUBEDIT := stubedit

# Phase 1 flags — DO NOT add -ffast-math here. The Phase 1 exit criterion is
# byte-identical stdout vs. upstream's native runq.c build, and fp reassociation
# breaks that. -ffast-math re-enables in Phase 3 behind a tolerance-based diff.
#
# -ffloat-store forces x87 intermediates to round to 32-bit on store,
# reconciling DJGPP's x87 FPU with the SSE2-strict host reference (the
# committed golden was generated by a native x86-64 gcc build, which
# defaults to -mfpmath=sse and is therefore strict IEEE-754 32-bit).
# Without it, 80-bit extended intermediates accumulate ULP-level drift
# that eventually flips a softmax argmax around token 35 and the
# generation diverges. Confirmed required via a native-side
# -m32 -mfpmath=387 -ffloat-store experiment that reproduces the golden
# byte-for-byte; see docs/phase1-notes.md.
CFLAGS   := -march=pentium -O2 -fomit-frame-pointer -ffloat-store -Wall -Isrc
LDFLAGS  :=
LDLIBS   := -lm

# Phase 1 post-link step: bump the DPMI min stack from 256K to 2048K. The
# default is way too small for llama2-scale activations on DPMI.
MINSTACK := 2048k

# --- Sources ------------------------------------------------------------------

# vellm.c is a self-contained fork of vendor/llama2.c/runq.c with minimum
# DOS-required deltas. It does NOT link against the Phase-0 scaffolding
# (src/matmul.c, src/timing.c, src/tokenizer.c) — those get subsumed/replaced
# in later phases; the Phase 1 port stays single-TU so the
# `grep 'DOS-PORT:' src/vellm.c` audit is complete.
# (src/quant.{c,h} were deleted in Phase 2 — runq.c's Q8_0 format is native;
# vellm never needs its own quant path.)
SRC_MAIN  := src/vellm.c

# --- Targets ------------------------------------------------------------------

# Default target: the real Phase 1 artifact. `make hello` is still wired up
# for the Phase 0 smoke test.
.PHONY: all
all: vellm.exe

.PHONY: vellm
vellm: vellm.exe

vellm.exe: $(SRC_MAIN)
	@test -s $< || (echo "error: $< is empty — see task #4 (fork runq.c)" >&2; exit 1)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $< $(LDLIBS)
	$(STUBEDIT) $@ minstack=$(MINSTACK)

# Pattern rule for .c -> .o under DJGPP (kept for future multi-TU work).
%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

# --- Phase 0 smoke test -------------------------------------------------------

.PHONY: hello
hello: hello.exe

hello.exe: tests/smoketest/hello.c
	$(CC) $(CFLAGS) -o $@ $<
	$(STUBEDIT) $@ minstack=256k

# --- Install / dist -----------------------------------------------------------
#
# `make install CF=/mnt/cf` copies the Phase 1 runtime payload onto a
# mounted CF card. We do NOT expect this Makefile to mount anything; that's
# the operator's job. The payload is:
#
#   VELLM.EXE        — the DJGPP-built inference binary
#   CWSDPMI.EXE      — required DPMI host; must ship alongside vellm.exe
#   CWSDPMI.DOC      — cwsdpmi license/readme (THIRD-PARTY.md requirement)
#   STORIES15M_Q80.BIN — TinyStories Q8_0 checkpoint (~15 MB, from karpathy/llama2.c release)
#   TOKENIZER.BIN    — 32K-vocab SentencePiece tokenizer
#   RUN.BAT          — canned invocation with the Phase 1 golden-test args

CF ?=

MODEL_BIN := models/stories15M_q80.bin
TOKENIZER_BIN := models/tokenizer.bin
CWSDPMI_EXE := vendor/cwsdpmi/cwsdpmi.exe
CWSDPMI_DOC := vendor/cwsdpmi/cwsdpmi.doc

# Canonical Phase 1 invocation. Flag names track runq.c argv verbatim
# (lowercase: -z tokenizer, -t temp, -s seed, -n steps, -i prompt).
# DOS COMMAND.COM passes argv through literally so lowercase works.
RUN_BAT_CMD := VELLM.EXE STORIES15M_Q80.BIN -z TOKENIZER.BIN -t 0 -s 42 -n 200 -i "Once upon a time"

.PHONY: install
install: vellm.exe
ifeq ($(strip $(CF)),)
	@echo "error: set CF=/path/to/cf/mount (e.g. make install CF=/mnt/cf)" >&2; exit 1
else
	@test -d "$(CF)" || (echo "error: CF=$(CF) is not a directory" >&2; exit 1)
	@test -f "$(CWSDPMI_EXE)" || (echo "error: $(CWSDPMI_EXE) missing" >&2; exit 1)
	@test -f "$(CWSDPMI_DOC)" || (echo "error: $(CWSDPMI_DOC) missing" >&2; exit 1)
	@test -f "$(MODEL_BIN)"   || (echo "error: $(MODEL_BIN) missing — download from karpathy/llama2.c release" >&2; exit 1)
	@test -f "$(TOKENIZER_BIN)" || (echo "error: $(TOKENIZER_BIN) missing — download from karpathy/llama2.c release" >&2; exit 1)
	install -m 0644 vellm.exe        "$(CF)/VELLM.EXE"
	install -m 0644 $(CWSDPMI_EXE)   "$(CF)/CWSDPMI.EXE"
	install -m 0644 $(CWSDPMI_DOC)   "$(CF)/CWSDPMI.DOC"
	install -m 0644 $(MODEL_BIN)     "$(CF)/STORIES15M_Q80.BIN"
	install -m 0644 $(TOKENIZER_BIN) "$(CF)/TOKENIZER.BIN"
	@printf '@echo off\r\nset DPMI=CWSDPMI.EXE\r\n%s\r\n' '$(RUN_BAT_CMD)' > "$(CF)/RUN.BAT"
	@echo "installed vellm payload to $(CF)"
endif

.PHONY: dist
dist: vellm.exe
	@test -f "$(CWSDPMI_EXE)" || (echo "error: $(CWSDPMI_EXE) missing" >&2; exit 1)
	@test -f "$(CWSDPMI_DOC)" || (echo "error: $(CWSDPMI_DOC) missing" >&2; exit 1)
	@test -f "$(MODEL_BIN)"   || (echo "error: $(MODEL_BIN) missing — download from karpathy/llama2.c release" >&2; exit 1)
	@test -f "$(TOKENIZER_BIN)" || (echo "error: $(TOKENIZER_BIN) missing — download from karpathy/llama2.c release" >&2; exit 1)
	@mkdir -p dist
	@rm -f dist/vellm.zip
	@tmp=$$(mktemp -d) && \
		cp vellm.exe            "$$tmp/VELLM.EXE" && \
		cp $(CWSDPMI_EXE)       "$$tmp/CWSDPMI.EXE" && \
		cp $(CWSDPMI_DOC)       "$$tmp/CWSDPMI.DOC" && \
		cp $(MODEL_BIN)         "$$tmp/STORIES15M_Q80.BIN" && \
		cp $(TOKENIZER_BIN)     "$$tmp/TOKENIZER.BIN" && \
		printf '@echo off\r\nset DPMI=CWSDPMI.EXE\r\n%s\r\n' '$(RUN_BAT_CMD)' > "$$tmp/RUN.BAT" && \
		(cd "$$tmp" && zip -q -r "$(CURDIR)/dist/vellm.zip" .) && \
		rm -rf "$$tmp" && \
		echo "dist/vellm.zip"

# --- Housekeeping -------------------------------------------------------------

.PHONY: clean
clean:
	rm -f src/*.o tests/smoketest/*.o
	rm -f vellm.exe hello.exe
	rm -f run_host
	rm -rf build dist
