#!/usr/bin/env bash
#
# tests/run-golden.sh — Phase 1 byte-identical correctness gate.
#
# Runs vellm.exe headless under DOSBox-X on the canonical prompt and diffs
# captured stdout against tests/golden/once_upon_a_time.txt (which was
# generated by the native Linux build of upstream vendor/llama2.c/runq.c at
# the pinned UPSTREAM_SHA).
#
# The only normalization applied before diffing is CRLF -> LF: DJGPP opens
# stdout in text mode on DOS, so \n in vellm.exe's printf() becomes \r\n in
# the captured STDOUT.TXT. Stripping the \r is a line-ending convention
# alignment only; it does NOT mask any numerical difference in the token
# stream. No other tolerance or transformation is applied.
#
# Exits 0 on pass, nonzero on any difference.

set -euo pipefail

cd "$(dirname "$0")/.."

GOLDEN="tests/golden/once_upon_a_time.txt"
MODEL="models/stories15M_q80.bin"
TOKENIZER="models/tokenizer.bin"
CWSDPMI="vendor/cwsdpmi/cwsdpmi.exe"

# --- Build artifacts on demand ------------------------------------------------

if [[ ! -f vellm.exe ]]; then
    echo "run-golden: vellm.exe missing — running 'make'" >&2
    make >&2 || { echo "run-golden: 'make' failed" >&2; exit 1; }
fi

if [[ ! -f run_host ]]; then
    echo "run-golden: run_host missing — running 'make -f Makefile.host'" >&2
    make -f Makefile.host >&2 || {
        echo "run-golden: 'make -f Makefile.host' failed" >&2
        exit 1
    }
fi

# --- Data / vendor files ------------------------------------------------------

MISSING=()
for f in "$GOLDEN" "$MODEL" "$TOKENIZER" "$CWSDPMI"; do
    [[ -f "$f" ]] || MISSING+=("$f")
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
    echo "run-golden: missing required files:" >&2
    for f in "${MISSING[@]}"; do
        echo "  $f" >&2
    done
    echo "" >&2
    echo "  Golden (tests/golden/*.txt) is regenerated by task #3 via run_host." >&2
    echo "  Model/tokenizer live under models/ — download from karpathy/llama2.c release." >&2
    echo "  CWSDPMI is vendored at vendor/cwsdpmi/." >&2
    exit 1
fi

# --- Run vellm.exe under DOSBox-X --------------------------------------------

RAW="$(mktemp -t vellm-golden-raw.XXXXXX)"
ACTUAL="$(mktemp -t vellm-golden-actual.XXXXXX)"
# The host-side basenames `stories15M_q80.bin` and `tokenizer.bin` both exceed
# the DOS 8.3 budget and get auto-mangled to STORIE~N.BIN / TOKENI~N.BIN when
# staged into C:\ (DOSBox-X's default LFN=auto does not expose long names to
# COMMAND.COM). Restaging under 8.3-safe names keeps the RUN.BAT invocation
# independent of mangling order.
SHORTSTAGE="$(mktemp -d -t vellm-golden-stage.XXXXXX)"
trap 'rm -rf "$RAW" "$ACTUAL" "$SHORTSTAGE"' EXIT
cp "$MODEL"     "$SHORTSTAGE/MODEL.BIN"
cp "$TOKENIZER" "$SHORTSTAGE/TOKEN.BIN"

echo "run-golden: invoking vellm.exe under DOSBox-X..." >&2

# Flag names match runq.c argv verbatim (lowercase). DOS COMMAND.COM passes
# argv through literally so lowercase works even from a .BAT file.
tools/dosbox-run.sh \
    --exe vellm.exe \
    --args 'MODEL.BIN -z TOKEN.BIN -t 0 -s 42 -n 200 -i "Once upon a time"' \
    --include "$SHORTSTAGE/MODEL.BIN" \
    --include "$SHORTSTAGE/TOKEN.BIN" \
    --stdout "$RAW"

# --- Normalize and diff -------------------------------------------------------

# Strip trailing CR on every line (DJGPP text-mode \n -> \r\n on DOS).
# Do NOT apply any other transformation — the point is byte-identical tokens.
tr -d '\r' < "$RAW" > "$ACTUAL"

if diff -q "$GOLDEN" "$ACTUAL" >/dev/null; then
    echo "PASS: byte-identical"
    exit 0
else
    echo "FAIL: vellm.exe stdout differs from $GOLDEN" >&2
    echo "      first 30 lines of 'diff -u $GOLDEN <actual>':" >&2
    diff -u "$GOLDEN" "$ACTUAL" | head -30 >&2 || true
    exit 1
fi
