#!/usr/bin/env bash
#
# tests/run-golden.sh — vellm.exe correctness gate.
#
# Two checks, tried in order. Gate passes if either one passes.
#
#   (1) PRIMARY (Phase 1 byte-identical fingerprint).
#       First 192 bytes of captured stdout must be byte-identical to
#       tests/golden/once_upon_a_time.txt.  This is the fp-strict check
#       that all of Phase 1 / Phase 2 satisfied and that -ffast-math-free
#       builds will continue to satisfy.  Passing here short-circuits — we
#       don't even look at the tolerance check.
#
#   (2) TOLERANCE (Phase 3+, for -ffast-math and other lossy
#       optimizations).  Two conditions, both required:
#         (a) first 30 bytes byte-identical to golden — catches total
#             regressions (tokenizer, embedding, first layers).
#         (b) ≥ 97% positional agreement on whitespace-split word tokens
#             between captured stdout and golden.
#       See docs/phase3-notes.md for why we chose whitespace-word agreement
#       over BPE re-encoding or logit-trace comparison (simplest gate that
#       distinguishes good-optimization divergence from bad-optimization
#       garbage).
#
# Normalization on $ACTUAL: CRLF -> LF only.  DJGPP opens stdout in text
# mode on DOS, so vellm.exe's \n becomes \r\n in STDOUT.TXT.  Stripping
# the \r is a line-ending alignment only; it does NOT mask any numerical
# difference.
#
# Exits 0 on pass (either gate), nonzero on failure.

set -euo pipefail

cd "$(dirname "$0")/.."

GOLDEN="tests/golden/once_upon_a_time.txt"
MODEL="models/stories15M_q80.bin"
TOKENIZER="models/tokenizer.bin"
CWSDPMI="vendor/cwsdpmi/cwsdpmi.exe"

# Gate tunables — see header comment for rationale.
PRIMARY_BYTES=192        # Phase 1 byte-identical fingerprint length.
TOLERANCE_PREFIX_BYTES=30  # must match even in tolerance mode.
TOLERANCE_AGREE_PCT=97   # ≥ this many % of positional word tokens must agree.

# --- Build artifacts on demand ------------------------------------------------

if [[ ! -f vellm.exe ]]; then
    echo "run-golden: vellm.exe missing — running 'make'" >&2
    make >&2 || { echo "run-golden: 'make' failed" >&2; exit 1; }
fi

if [[ ! -f run_host ]]; then
    echo "run-golden: run_host missing — running 'make -f Makefile.host'" >&2
    make -f Makefile.host >&2 || {
        echo "run-golden: 'make -f Makefile.host' failed" >&2
        exit 1
    }
fi

# --- Data / vendor files ------------------------------------------------------

MISSING=()
for f in "$GOLDEN" "$MODEL" "$TOKENIZER" "$CWSDPMI"; do
    [[ -f "$f" ]] || MISSING+=("$f")
done

if [[ ${#MISSING[@]} -gt 0 ]]; then
    echo "run-golden: missing required files:" >&2
    for f in "${MISSING[@]}"; do
        echo "  $f" >&2
    done
    echo "" >&2
    echo "  Golden (tests/golden/*.txt) is regenerated by task #3 via run_host." >&2
    echo "  Model/tokenizer live under models/ — download from karpathy/llama2.c release." >&2
    echo "  CWSDPMI is vendored at vendor/cwsdpmi/." >&2
    exit 1
fi

# --- Run vellm.exe under DOSBox-X --------------------------------------------

RAW="$(mktemp -t vellm-golden-raw.XXXXXX)"
ACTUAL="$(mktemp -t vellm-golden-actual.XXXXXX)"
# The host-side basenames `stories15M_q80.bin` and `tokenizer.bin` both exceed
# the DOS 8.3 budget and get auto-mangled to STORIE~N.BIN / TOKENI~N.BIN when
# staged into C:\ (DOSBox-X's default LFN=auto does not expose long names to
# COMMAND.COM). Restaging under 8.3-safe names keeps the RUN.BAT invocation
# independent of mangling order.
SHORTSTAGE="$(mktemp -d -t vellm-golden-stage.XXXXXX)"
PREFIX_GOLDEN="$(mktemp -t vellm-golden-prefix.XXXXXX)"
PREFIX_ACTUAL="$(mktemp -t vellm-actual-prefix.XXXXXX)"
TOK_GOLDEN="$(mktemp -t vellm-golden-toks.XXXXXX)"
TOK_ACTUAL="$(mktemp -t vellm-actual-toks.XXXXXX)"
trap 'rm -f "$RAW" "$ACTUAL" "$PREFIX_GOLDEN" "$PREFIX_ACTUAL" "$TOK_GOLDEN" "$TOK_ACTUAL"; rm -rf "$SHORTSTAGE"' EXIT

cp "$MODEL"     "$SHORTSTAGE/MODEL.BIN"
cp "$TOKENIZER" "$SHORTSTAGE/TOKEN.BIN"

echo "run-golden: invoking vellm.exe under DOSBox-X..." >&2

# Flag names match runq.c argv verbatim (lowercase). DOS COMMAND.COM passes
# argv through literally so lowercase works even from a .BAT file.
tools/dosbox-run.sh \
    --exe vellm.exe \
    --args 'MODEL.BIN -z TOKEN.BIN -t 0 -s 42 -n 200 -i "Once upon a time"' \
    --include "$SHORTSTAGE/MODEL.BIN" \
    --include "$SHORTSTAGE/TOKEN.BIN" \
    --stdout "$RAW"

# --- Normalize ----------------------------------------------------------------

# Strip trailing CR on every line (DJGPP text-mode \n -> \r\n on DOS).
# Do NOT apply any other transformation.
tr -d '\r' < "$RAW" > "$ACTUAL"

ACTUAL_SIZE=$(wc -c < "$ACTUAL")
if [[ "$ACTUAL_SIZE" -lt "$PRIMARY_BYTES" ]]; then
    echo "FAIL: vellm.exe produced only $ACTUAL_SIZE bytes; need >= $PRIMARY_BYTES" >&2
    echo "      (full -n 200 run should produce ~677 bytes of text)" >&2
    exit 1
fi

# --- (1) PRIMARY gate: byte-identical 192-byte prefix ------------------------

head -c "$PRIMARY_BYTES" "$GOLDEN" > "$PREFIX_GOLDEN"
head -c "$PRIMARY_BYTES" "$ACTUAL" > "$PREFIX_ACTUAL"

if diff -q "$PREFIX_GOLDEN" "$PREFIX_ACTUAL" >/dev/null; then
    echo "PASS (primary): first $PRIMARY_BYTES bytes byte-identical to $GOLDEN"
    echo "                (full stdout is $ACTUAL_SIZE bytes)"
    exit 0
fi

# --- (2) TOLERANCE gate ------------------------------------------------------
#
# Primary failed.  Fall back to: short prefix match + ≥97% word agreement.
# This is the gate that lets -ffast-math / int8 KV cache / matmul reassoc
# through — they can perturb fp accumulation enough to shift one or two
# tokens in the middle of the 200-token stream without being semantically
# wrong.  A bad optimization that corrupts the compute path produces
# garbage, which fails both (2a) and (2b) hard.

echo "run-golden: primary 192-byte match failed, falling back to tolerance gate" >&2

# (2a) first 30 bytes must still match byte-for-byte.
SHORT_GOLDEN="$(mktemp -t vellm-golden-short.XXXXXX)"
SHORT_ACTUAL="$(mktemp -t vellm-actual-short.XXXXXX)"
# shellcheck disable=SC2064
trap "rm -f \"\$RAW\" \"\$ACTUAL\" \"\$PREFIX_GOLDEN\" \"\$PREFIX_ACTUAL\" \"\$TOK_GOLDEN\" \"\$TOK_ACTUAL\" \"\$SHORT_GOLDEN\" \"\$SHORT_ACTUAL\" ; rm -rf \"\$SHORTSTAGE\"" EXIT

head -c "$TOLERANCE_PREFIX_BYTES" "$GOLDEN" > "$SHORT_GOLDEN"
head -c "$TOLERANCE_PREFIX_BYTES" "$ACTUAL" > "$SHORT_ACTUAL"

if ! diff -q "$SHORT_GOLDEN" "$SHORT_ACTUAL" >/dev/null; then
    echo "FAIL (tolerance 2a): first $TOLERANCE_PREFIX_BYTES bytes also differ — not just fp drift" >&2
    diff -u "$SHORT_GOLDEN" "$SHORT_ACTUAL" | head -20 >&2 || true
    echo "FAIL: first $PRIMARY_BYTES bytes of vellm.exe stdout differ from $GOLDEN" >&2
    diff -u "$PREFIX_GOLDEN" "$PREFIX_ACTUAL" | head -30 >&2 || true
    exit 1
fi

# (2b) positional word-token agreement.
#
# Whitespace-split each file into positional tokens, count positions where
# both sides have the same word.  This is a coarser granularity than BPE
# tokens (140 words vs 200 BPE tokens in the 692-byte reference) but is
# simple, doesn't need the tokenizer, and tracks semantic divergence well:
# one flipped argmax mid-stream typically perturbs 1–3 subsequent words
# before the text re-aligns.  Drop-in upgrade path to BPE-token comparison
# or logit-trace diff is noted in docs/phase3-notes.md if this proves too
# coarse.
awk 'BEGIN{RS="[[:space:]]+"} /./ {print}' "$GOLDEN" > "$TOK_GOLDEN"
awk 'BEGIN{RS="[[:space:]]+"} /./ {print}' "$ACTUAL" > "$TOK_ACTUAL"

TOTAL_GOLDEN=$(wc -l < "$TOK_GOLDEN")
TOTAL_ACTUAL=$(wc -l < "$TOK_ACTUAL")

# Use the shorter of the two as the comparison length so truncation is
# visible in the agreement count rather than silently ignored.
if [[ "$TOTAL_GOLDEN" -le "$TOTAL_ACTUAL" ]]; then
    TOTAL=$TOTAL_GOLDEN
else
    TOTAL=$TOTAL_ACTUAL
fi

AGREE=$(paste "$TOK_GOLDEN" "$TOK_ACTUAL" | \
        awk -F'\t' 'NR<=total && $1==$2 {n++} END{print n+0}' total="$TOTAL")

# Required-agree threshold = ceil(pct * total / 100).
REQUIRED=$(( (TOTAL_GOLDEN * TOLERANCE_AGREE_PCT + 99) / 100 ))

# Fail early if the vellm output is markedly shorter than the golden — that
# indicates a crash or hang, not a tolerable fp drift.  Shortness that would
# drive agreement below threshold is caught by the next check, but calling
# it out explicitly helps debugging.
if [[ "$TOTAL_ACTUAL" -lt "$REQUIRED" ]]; then
    echo "FAIL (tolerance 2b): vellm output has only $TOTAL_ACTUAL word-tokens, need >= $REQUIRED" >&2
    exit 1
fi

if [[ "$AGREE" -ge "$REQUIRED" ]]; then
    echo "PASS (tolerance): $AGREE / $TOTAL_GOLDEN word-tokens agree" \
         "(>= $REQUIRED required, ${TOLERANCE_AGREE_PCT}%)"
    echo "                  first $TOLERANCE_PREFIX_BYTES bytes byte-identical"
    echo "                  primary 192-byte gate failed — expected if this build has"
    echo "                  -ffast-math or another lossy optimization enabled"
    exit 0
fi

echo "FAIL (tolerance 2b): only $AGREE / $TOTAL_GOLDEN word-tokens agree" \
     "(need >= $REQUIRED, ${TOLERANCE_AGREE_PCT}%)" >&2
echo "                     primary 192-byte gate also failed" >&2
echo "                     first 30 lines of 'diff -u <golden> <actual>':" >&2
diff -u "$GOLDEN" "$ACTUAL" | head -30 >&2 || true
exit 1
